Repository openshift/openshift-restclient-python, pull requests merged in 2018-09, with the labels that each got.

#196 Provide 'append_hash' for ConfigMaps and Secrets
  openshift/helper/hashes.py
  test-requirements.txt
  test/unit/test_hashes.py
  test/unit/test_marshal.py
Labels: needs-ok-to-test, size/L

#208 Add behavior-based tests for dynamic client
  .travis.yml
  test-requirements.txt
  test/functional/conftest.py
  test/functional/dynamic/conftest.py
  test/functional/dynamic/create.feature
  test/functional/dynamic/definitions/route.openshift.io_v1_Route_test.yaml
  test/functional/dynamic/definitions/route.openshift.io_v1_Route_test_replace.yaml
  test/functional/dynamic/definitions/v1_Pod_test.yaml
  test/functional/dynamic/definitions/v1_Pod_test_patch.yaml
  test/functional/dynamic/delete.feature
  test/functional/dynamic/patch.feature
  test/functional/dynamic/replace.feature
  test/functional/dynamic/test_create.py
  test/functional/dynamic/test_delete.py
  test/functional/dynamic/test_patch.py
  test/functional/dynamic/test_replace.py
  test/functional/generated/conftest.py
  test/functional/generated/test_examples.py
  tox.ini
Labels: size/XL

#207 Allow less strict kubernetes version requirements
  requirements.txt
Labels: size/XS

#211 DynamicApiError: add a short_message method
  openshift/dynamic/exceptions.py
Labels: size/S

#199 Add validate helper function
  openshift/dynamic/client.py
  openshift/dynamic/exceptions.py
Labels: size/M
