Repository openshift/openshift-restclient-python, pull requests merged in 2018-10, with the labels that each got.

#213 Add support for *List kinds
  openshift/dynamic/client.py
  test/functional/dynamic/conftest.py
  test/functional/dynamic/create.feature
  test/functional/dynamic/definitions/route.openshift.io_v1_RouteList_test.yaml
  test/functional/dynamic/definitions/route.openshift.io_v1_RouteList_test_replace.yaml
  test/functional/dynamic/definitions/v1_PodList_test.yaml
  test/functional/dynamic/definitions/v1_PodList_test_patch.yaml
  test/functional/dynamic/definitions/v1_Pod_test_patch.yaml
  test/functional/dynamic/delete.feature
  test/functional/dynamic/patch.feature
  test/functional/dynamic/replace.feature
  test/functional/dynamic/test_create.py
  test/functional/dynamic/test_delete.py
  test/functional/dynamic/test_patch.py
  test/functional/dynamic/test_replace.py
Labels: size/XL

#227 ResourceContainer does not contain delete method
  README.md
Labels: lgtm, size/XS

#225 Do not decode response data in Python2
  openshift/dynamic/client.py
Labels: needs-ok-to-test, size/XS
