Repository openshift/openshift-restclient-python, pull requests merged in 2018-11, with the labels that each got.

#221 First stab at watch implementation
  README.md
  openshift/dynamic/client.py
Labels: lgtm, size/M

#231 When searching for resources, prefer non-List matches
  openshift/dynamic/client.py
  test/unit/test_resource_container.py
Labels: size/M

#235 Improve README wrt custom resources and login
  README.md
Labels: size/L

#238 add automatic caching for discovery requests, refreshing on a miss
  openshift/dynamic/client.py
Labels: size/L
