Repository openshift/openshift-restclient-python, pull requests merged in 2018-08, with the labels that each got.

#192 Fix decode issue for #191
  openshift/client/api_client.py
Labels: size/XS

#197 Rename async to async_req for compatibility with python3 and kubernetes 7
  .travis.yml
  openshift/README.md
  openshift/__init__.py
  openshift/client/apis/apps_openshift_io_api.py
  openshift/client/apis/apps_openshift_io_v1_api.py
  openshift/client/apis/authorization_openshift_io_api.py
  openshift/client/apis/authorization_openshift_io_v1_api.py
  openshift/client/apis/build_openshift_io_api.py
  openshift/client/apis/build_openshift_io_v1_api.py
  openshift/client/apis/image_openshift_io_api.py
  openshift/client/apis/image_openshift_io_v1_api.py
  openshift/client/apis/network_openshift_io_api.py
  openshift/client/apis/network_openshift_io_v1_api.py
  openshift/client/apis/oapi_api.py
  openshift/client/apis/oauth_openshift_io_api.py
  openshift/client/apis/oauth_openshift_io_v1_api.py
  openshift/client/apis/project_openshift_io_api.py
  openshift/client/apis/project_openshift_io_v1_api.py
  openshift/client/apis/quota_openshift_io_api.py
  openshift/client/apis/quota_openshift_io_v1_api.py
  openshift/client/apis/route_openshift_io_api.py
  openshift/client/apis/route_openshift_io_v1_api.py
  openshift/client/apis/security_openshift_io_api.py
  openshift/client/apis/security_openshift_io_v1_api.py
  openshift/client/apis/template_openshift_io_api.py
  openshift/client/apis/template_openshift_io_v1_api.py
  openshift/client/apis/user_openshift_io_api.py
  openshift/client/apis/user_openshift_io_v1_api.py
  openshift/dynamic/client.py
  python-openshift.spec
  requirements.txt
  scripts/constants.py
  scripts/update-version.sh
  setup.py
  test/functional/test_examples.py
  tox.ini
Labels: size/XXL

#201 Allow creates on subresources properly
  openshift/dynamic/client.py
Labels: size/S

#202 Allow creates on subresources properly (#201)
  openshift/dynamic/client.py
Labels: size/S
