Repository openshift/openshift-restclient-python, pull requests merged in 2019-01, with the labels that each got.

#252 Remove shebang + main function from dynamic client
  openshift/dynamic/client.py
Labels: size/M

#250 Lower case URLs
  openshift/dynamic/client.py
Labels: size/XS

#258 [release-0.8] add automatic caching for discovery requests, refreshing on a miss
  openshift/dynamic/client.py
Labels: size/L

#259 take md5 of cache_id to prevent it from being too long
  openshift/dynamic/client.py
Labels: size/XS

#261 fix setup.py and rpm spec for removed files and packages
  python-openshift.spec
  setup.py
Labels: size/S

#242 RPM Spec updates
  python-openshift.spec
Labels: size/L

#248 RPM Spec updates for 0.8 release branch
  python-openshift.spec
Labels: size/L

#260 hash cache name to prevent it from becoming too long
  openshift/dynamic/client.py
Labels: size/XS

#263 Fix macro syntax errors
  python-openshift.spec
Labels: size/XS
