Repository openshift/openshift-restclient-python, pull requests merged in 2019-12, with the labels that each got.

#342 Remove md5, which fails in FIPS environment
  openshift/dynamic/discovery.py
Labels: lgtm, size/XS

#339 Apply should work if resources change in between
  openshift/dynamic/apply.py
  openshift/dynamic/client.py
  openshift/dynamic/exceptions.py
  test/unit/test_apply.py
Labels: size/L

#343 RM md5 which is not allowed in fips
  openshift/dynamic/client.py
Labels: lgtm, size/XS

#344 RM md5 which is not allowed in fips
  openshift/dynamic/client.py
Labels: lgtm, size/XS

#347 Bump version
  openshift/README.md
  openshift/__init__.py
  python-openshift.spec
  scripts/constants.py
  setup.py
Labels: lgtm, size/S

#341 Take last applied configuration into account when patching
  openshift/dynamic/apply.py
  test/unit/test_apply.py
Labels: size/L

#351 Fix apply to cope better with missing last_applied entries
  openshift/dynamic/apply.py
  test/unit/test_apply.py
Labels: size/M
