Repository openshift/openshift-restclient-python, pull requests merged in 2019-02, with the labels that each got.

#237 Add a message about kubernetes version not being supported
  openshift/dynamic/client.py
Labels: needs-ok-to-test, size/XS

#264 Prevent API groups from growing stale
  openshift/dynamic/client.py
Labels: size/S

#267 Ignore broken cache
  openshift/dynamic/client.py
Labels: size/XS
