Repository openshift/openshift-restclient-python, pull requests merged in 2021-06, with the labels that each got.

#406 Add an option to provide "Accept" header to client request
  openshift/dynamic/client.py
Labels: approved, do-not-merge/hold, lgtm

#407 Handle header_params same as upstream
  openshift/dynamic/client.py
Labels: approved

#393 fix typo in README.md
  README.md
Labels: lifecycle/rotten
